
version: "3"
services:
  staticsloth:
    container_name: staticsloth
    # image: denbeke/staticsloth
    build: .
    ports:
      - "1234:1234"
    environment:
      - ACCESS_LOG=1
    volumes: 
      - .:/var/www/html:ro